In [3]:
import numpy as np

In [22]:
score=np.random.randint(40,101,100)
print(score)

[ 44  43  75  45  52  48  52  50  72  61  93  72  69  59  87  50  48  78
  98  83  79  84  77  67  90  99  52  72  47  99  40  40  45  75  79  96
  58  40  91  55  95  87  89  71 100  94  67  69  46  61  99  83  85  56
  95  79  49  72  95  64  73  44  43  65  78  62  82  58  86  47  56  70
  65 100  48  53  68  76  96  64  73  90  65  97  40  57  60  56  81 100
  72  58  59  79  63  40  71  90  90  90]


In [23]:
mean_score = np.mean(score)
print(mean_score)

69.85


In [24]:
median_score = np.median(score)
print(median_score)

70.5


In [25]:
standard_deviation = np.std(score)
print(standard_deviation)

18.083901680776744


In [26]:
above_average = score[score > mean_score]
count_above_average = len(above_average)
print(count_above_average)
print(above_average)

51
[ 75  72  93  72  87  78  98  83  79  84  77  90  99  72  99  75  79  96
  91  95  87  89  71 100  94  99  83  85  95  79  72  95  73  78  82  86
  70 100  76  96  73  90  97  81 100  72  79  71  90  90  90]


In [27]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [29]:
c_transpose = c.T
print(c_transpose)

[[19 43]
 [22 50]]


In [31]:
result=[]
for i in range(10000000):
    result.append(i*2)

In [32]:
arr=np.ones((2,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr = np.array([np.ones(5), np.zeros(5)])
print(arr)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [38]:
a = np.array([[50,60],[20,30]])
b = np.array([[10,80],[40,70]])
c = np.add(a,b)
#c = a+b
print(c)


[[ 60 140]
 [ 60 100]]


In [39]:
arr = np.array([np.ones(2), np.zeros(2)])
print(arr)

[[1. 1.]
 [0. 0.]]


In [40]:
a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
c=np.add(a,b)
#add
print(c)

[[ 60  80]
 [100 120]]


In [41]:
a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
c=np.divide(a,b)
#divide
print(c)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [42]:
a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
c=np.dot(a,b)
#dot
print(c)

[[1900 2200]
 [4300 5000]]


In [46]:
marks = np.random.randint(0, 101, (5,3))
subjects = ['Math', 'Science', 'English']
print("Marks:")    
print(subjects)
print(marks)

total = np.sum(marks, axis=1)

percentage = total / 3

print("\nStudent\tTotal\tPercentage")
for i in range(5):
    print(f"{i+1}\t{total[i]}\t{percentage[i]:.2f}%")

Marks:
['Math', 'Science', 'English']
[[24  3 65]
 [ 3 15 45]
 [75 69 74]
 [95 27 35]
 [23 10 79]]

Student	Total	Percentage
1	92	30.67%
2	63	21.00%
3	218	72.67%
4	157	52.33%
5	112	37.33%


In [50]:
arr = np.random.randint(50,101,30)
print("Original Array:")
print(arr)

unique_values = np.unique(arr)
print("\nUnique Values:")
print(unique_values)

Original Array:
[ 76  97  93  68  89  95  94  93  50  83  59 100  50  50  92  99  96  71
  70  50  72  58  83  53  51  51  74  90  75  59]

Unique Values:
[ 50  51  53  58  59  68  70  71  72  74  75  76  83  89  90  92  93  94
  95  96  97  99 100]
